"""empty message

Revision ID: 366526923ff1
Revises: 
Create Date: 2022-06-08 21:44:47.083338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366526923ff1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'description',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
